name = "STLC"
version = "0.1.0"
defaultTargets = ["stlc"]

[[lean_lib]]
name = "STLC"

[[lean_exe]]
name = "stlc"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.17.0"
